better organization

diff --git a/shell/sdn b/shell/sdn
--- a/shell/sdn
+++ b/shell/sdn
@@ -3,6 +3,7 @@
 # ./sdn [-f]
 # Shut down. With no argument, wait for Firefox to quit.
 
+PROG_NAME='sdn'
 debug=true
 
 # handle arguments
@@ -13,26 +14,21 @@ do
         -f) wait=false
             shift
             ;;
-        *)  echo 'bad usage' >&2
+        *)  echo "${PROG_NAME}: bad usage" >&2
             exit 2
             ;;
     esac
 done
 
-# wait for Firefox to quit
-while "${wait}"
-do
-    #~ if [ "$(ps ax | grep -ic firefox)" -ge 2]; then
-    if ps ax | grep -i firefox | grep -v grep; then
-        sleep 23
-    else
-        wait=false
-        echo -n 'Firefox does not seem to be running anymore.'
-        if "${debug}"; then
-            echo -n ' Shut down? [enter|ctrl-c] '
-            read ans
-        fi
-    fi
-done
+if ~/bin/wait_until_quit -p 23 'firefox'; then
+    echo -n "${PROG_NAME}: Firefox does not seem to be running anymore."
 
-shutdown now
+    if "${debug}"; then
+        echo -n ' Shut down? [enter|ctrl-c] '
+        read ans
+    fi
+
+    shutdown now
+else
+    echo "${PROG_NAME}: ‘wait_until_quit’ returned with error ‘${?}’." >&2
+fi
