completed waiting system

diff --git a/shell/sdn b/shell/sdn
--- a/shell/sdn
+++ b/shell/sdn
@@ -20,10 +20,12 @@ do
     esac
 done
 
-if ~/bin/wait_until_quit -p 1 'firefox'; then
-    echo -n "${PROG_NAME}: Firefox does not seem to be running anymore."
-else
-    echo "${PROG_NAME}: ‘wait_until_quit’ returned with error ‘${?}’." >&2
+if "${wait}"; then
+    if ~/bin/wait_until_quit 'firefox'; then
+        echo -n "${PROG_NAME}: Firefox does not seem to be running anymore."
+    else
+        echo "${PROG_NAME}: ‘wait_until_quit’ returned with error ‘${?}’." >&2
+    fi
 fi
 
 if "${debug}"; then
