stuff

diff --git a/shell/wait_until_quit b/shell/wait_until_quit
--- a/shell/wait_until_quit
+++ b/shell/wait_until_quit
@@ -3,39 +3,51 @@
 # wait_until_quit [OPTION]... <process_keyword>
 # Wait for the processes matching ‘process_keyword’ to quit.
 
+PROG_NAME="$(basename "${0}")"
+
+SUCCESS=0
+MAX_EXCEEDED=1
+USER_ERROR=2
+INTERRUPTION=3
+
+trap 'exit "${INTERRUPTION}"' HUP INT QUIT TERM
+
 _usage()
 {
     cat <<-EOF
 
-	wait_until_quit [OPTION]... <process_keyword>
-	Wait for the processes matching <process_keyword> to quit. (May behave weirdly due to self-referentiality issues.)
+	${PROG_NAME} [OPTION]... <process_keyword>
+	Wait for the processes matching <process_keyword> to quit.
 
 	<process_keyword>
-	    In the output returned by ‘ps ax’, <process_keyword> must identify the lines corresponding to the desired processes.
+	    In the output returned by ‘ps ax’, <process_keyword> is used to
+	    identify the lines corresponding to the desired processes. It must not
+	    start with a hyphen.
 	-l <limit> (default: 0)
-	    Number of matched processes to ignore: even if they still match <process_keyword> when the desired processes have quit, return with success.
+	    Number of matched processes to ignore: even if they still match
+	    <process_keyword> when the desired processes have quit, return with
+	    success. (Technically, the script ignores two more processes than
+	    <limit>, because the script itself and a process it generates are
+	    supposed to match too.)
 	-m <max> (default: 0)
-	    Maximal amount of checks to perform. If <max> is not specified or is 0, do not limit the number of checks.
+	    Maximal amount of checks to perform. If <max> is not specified or is
+	    0, do not limit the number of checks.
 	-p <period> (default: 3)
-	    number of seconds between the checks made to determine if the processes have quit.
+	    number of seconds between the checks made to determine if the
+	    processes have quit.
 	-q
 	    Print less output.
 	-h, --help
 	    display this help and exit
 
 	Exit status:
-	    0    success
-	    1    maximal amount of checks exceeded
-	    2    user error
+	    ${SUCCESS}    success
+	    ${MAX_EXCEEDED}    maximal amount of checks exceeded
+	    ${USER_ERROR}    user error
+	    ${INTERRUPTION}    external interruption
 
 	EOF
 }
-
-PROG_NAME='wait_until_quit'
-
-SUCCESS=0
-MAX_EXCEEDED=1
-USER_ERROR=2
 
 _helpAndExit()
 {
@@ -48,7 +60,7 @@ _wrongUsage()
     if [ "${#}" -eq 0 ]; then
         echo "${PROG_NAME}: error: bad usage." >&2
     else
-        printf '%s' '${PROG_NAME}: error: bad usage: '
+        printf '%s: error: bad usage: ' "${PROG_NAME}"
         # print each argument on a new line
         printf '%s\n' "${@}" >&2
     fi
@@ -65,17 +77,13 @@ _display()
     ps ax | grep -i "${process_keyword}"
 }
 
-if [ "${#}" -eq 0 ]; then
-    _helpAndExit
-fi
-
 limit=0
 max=0
 period=3
 verbose=true
 
 # handle arguments
-while [ "${#}" -ge 2 ]
+while [ "${#}" -ge 1 ]
 do
     arg="${1}"
     shift
@@ -118,14 +126,44 @@ do
         -q)
             verbose=false
             ;;
+        --)
+            if [ "${#}" -eq 1 ]; then
+                break
+            else
+                _wrongUsage "end of options (double hyphen) found whereas ${#} arguments remain instead of just one. Arguments:" "${@}"
+            fi
+            ;;
+        -?|--*) # unknown option
+            _wrongUsage "invalid option: ${arg}" >&2
+            _usage
+            exit 1
+            ;;
+        -??*)   # several short options
+            while [ "${arg}" != '-' ]   # parse
+            do
+                new_arg="${arg%?}"  # remove last option
+                option="${arg##${new_arg}}" # read it
+                # forget dashes and add option to the list of single options to process
+                [ "${option}" = '-' ] || set -- "-${option}" "${@}"
+                arg="${new_arg}"
+            done
+            ;;
         *)
-            _wrongUsage " invalid argument: “${arg}”."
+            if [ "${#}" -eq 0 ]; then
+                process_keyword="${arg}"
+            else
+                _wrongUsage " invalid argument: “${arg}”."
+            fi
             ;;
     esac
 done
 
-# take into account the grep process generated by the current script
-let 'limit++'
+if [ -z "${process_keyword}" ]; then
+    _wrongUsage "argument not found: <process_keyword>."
+fi
+
+# take into account the current script and the grep process it generates
+limit="$((limit+2))"
 
 # wait for processes to quit
 wait=true
@@ -133,14 +171,14 @@ i=0
 count="$(_countProcesses)"
 while [ "${count}" -gt "${limit}" ]
 do
-    let 'i++'
+    i="$((i+1))"
     if [ "${max}" -gt 0 ] && [ "${i}" -gt "${max}" ]; then
         "${verbose}" && echo "${PROG_NAME}: maximal amount of checks exceeded." >&2
         exit "${MAX_EXCEEDED}"
     fi
-    sleep "${period}"
     "${verbose}" && _display
     count="$(_countProcesses)"
+    sleep "${period}"
 done
 
 "${verbose}" && echo "${PROG_NAME}: success!"
