stuff

diff --git a/shell/wait_until_quit b/shell/wait_until_quit
--- a/shell/wait_until_quit
+++ b/shell/wait_until_quit
@@ -11,14 +11,15 @@ _usage()
 	Wait for the processes matching <process_keyword> to quit. (May behave weirdly due to self-referentiality issues.)
 
 	<process_keyword>
-	    in the output returned by ‘ps ax’, <process_keyword> must identify the lines corresponding to the desired processes.
-	-l <limit>
-	    (default: 0) number of matched processes to ignore: even if they still match <process_keyword> when the desired processes have quit, return with success.
-	-m <max>
-	    maximal amount of checks to perform.
-        If <max> is not specified or is 0, do not limit the number of checks.
-	-p <period>
-	    number of seconds between instances of checking if the processes have quit (default: 3).
+	    In the output returned by ‘ps ax’, <process_keyword> must identify the lines corresponding to the desired processes.
+	-l <limit> (default: 0)
+	    Number of matched processes to ignore: even if they still match <process_keyword> when the desired processes have quit, return with success.
+	-m <max> (default: 0)
+	    Maximal amount of checks to perform. If <max> is not specified or is 0, do not limit the number of checks.
+	-p <period> (default: 3)
+	    number of seconds between the checks made to determine if the processes have quit.
+	-q
+	    Print less output.
 	-h, --help
 	    display this help and exit
 
@@ -30,15 +31,17 @@ _usage()
 	EOF
 }
 
+PROG_NAME='wait_until_quit'
+
 MAX_EXCEEDED=1
 USER_ERROR=2
 
 _wrongUsage()
 {
     if [ "${#}" -eq 0 ]; then
-        echo 'Error: bad usage.' >&2
+        echo "${PROG_NAME}: error: bad usage." >&2
     else
-        printf '%s' 'Error: bad usage: '
+        printf '%s' '${PROG_NAME}: error: bad usage: '
         # print each argument on a new line
         printf '%s\n' "${@}" >&2
     fi
@@ -51,9 +54,20 @@ _countProcesses()
     ps ax | grep -ic "${process_keyword}"
 }
 
-period=3
-max=0
+_display()
+{
+    ps ax | grep -i "${process_keyword}"
+}
+
+if [ "${#}" -eq 0 ]; then
+    _usage
+    exit
+fi
+
 limit=0
+max=0
+period=3
+verbose=true
 
 # handle arguments
 while [ "${#}" -ge 2 ]
@@ -68,53 +82,43 @@ do
             exit
             ;;
         -l)
-            if [ "${#}" -ge 1 ]; then
-                case "${1}" in
-                    ''|*[!0-9]*)
-                        _wrongUsage "argument for option -l should be an unsigned integer (received: “${1}”)."
-                        ;;
-                    *)
-                        limit="${1}"
-                esac
-                shift
-            else
-                _wrongUsage "option -l takes an argument."
-            fi
+            case "${1}" in
+                ''|*[!0-9]*)
+                    _wrongUsage "argument for option -l should be an unsigned integer (received: “${1}”)."
+                    ;;
+                *)
+                    limit="${1}"
+            esac
+            shift
             ;;
         -m)
-            if [ "${#}" -ge 1 ]; then
-                case "${1}" in
-                    ''|*[!0-9]*)
-                        _wrongUsage "argument for option -m should be an unsigned integer (received: “${1}”)."
-                        ;;
-                    *)
-                        max="${1}"
-                esac
-                shift
-            else
-                _wrongUsage "option -l takes an argument."
-            fi
+            case "${1}" in
+                ''|*[!0-9]*)
+                    _wrongUsage "argument for option -m should be an unsigned integer (received: “${1}”)."
+                    ;;
+                *)
+                    max="${1}"
+            esac
+            shift
             ;;
         -p)
-            if [ "${#}" -ge 1 ]; then
-                case "${1}" in
-                    ''|*[!0-9]*)
-                        _wrongUsage "argument for option -p should be an unsigned integer (received: “${1}”)."
-                        ;;
-                    *)
-                        period="${1}"
-                esac
-                shift
-            else
-                _wrongUsage "option -l takes an argument."
-            fi
+            case "${1}" in
+                ''|*[!0-9]*)
+                    _wrongUsage "argument for option -p should be an unsigned integer (received: “${1}”)."
+                    ;;
+                *)
+                    period="${1}"
+            esac
+            shift
+            ;;
+        -q)
+            verbose=false
             ;;
         *)
             _wrongUsage " invalid argument: “${arg}”."
             ;;
     esac
 done
-process_keyword="${1}"
 
 # take into account the grep process generated by the current script
 let 'limit++'
@@ -122,11 +126,17 @@ let 'limit++'
 # wait for processes to quit
 wait=true
 i=0
-while [ "$(_countProcesses)" -gt "${limit}" ]
+count="$(_countProcesses)"
+while [ "${count}" -gt "${limit}" ]
 do
+    let 'i++'
     if [ "${max}" -gt 0 ] && [ "${i}" -gt "${max}" ]; then
+        "${verbose}" && echo "${PROG_NAME}: maximal amount of checks exceeded." >&2
         exit "${MAX_EXCEEDED}"
     fi
     sleep "${period}"
-    let 'i++'
+    "${verbose}" && _display
+    count="$(_countProcesses)"
 done
+
+"${verbose}" && echo "${PROG_NAME}: success!"
